/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Data.AssociadoData;
import Data.DependenteData;
import java.awt.Component;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MaqLab
 */
public class GereciamentoPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public GereciamentoPagamento() {
        initComponents();
    }

 



            /**
             * This method is called from within the constructor to initialize
             * the form. WARNING: Do NOT modify this code. The content of this
             * method is always regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbSelecione = new javax.swing.JComboBox();
        jL_tiposelecionado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTfiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Gerenciamento de Mensalidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(jLabel1)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jcbSelecione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Associado", "Dependente" }));

        jL_tiposelecionado.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jL_tiposelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jButton1.setText("Exibir Tudo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTfiltro.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jTfiltro.setForeground(new java.awt.Color(102, 102, 102));
        jTfiltro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfiltro.setText("Filtrar");
        jTfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfiltroActionPerformed(evt);
            }
        });
        jTfiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfiltroFocusLost(evt);
            }
        });
        jTfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfiltroKeyReleased(evt);
            }
        });

        jtb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jtb.setForeground(new java.awt.Color(0, 0, 255));
        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb);

        jButton2.setText("Limpar Tabela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jcbSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(271, 271, 271))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addComponent(jL_tiposelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGap(247, 247, 247)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jcbSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jL_tiposelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(255, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 try {
                if (jcbSelecione.getSelectedIndex()== 1) {
                    Vector cabecalho = new Vector();
                    cabecalho.add("Id");
                    cabecalho.add("Nome");
                    cabecalho.add("CPF");
                    cabecalho.add("status_da_mensalidade");
                    jtb.setModel(new DefaultTableModel(new AssociadoData().listar(), cabecalho));
                }
            

            if 
                (jcbSelecione.getSelectedIndex()== 2) {
                    Vector cabecalho = new Vector();
                    cabecalho.add("Id");
                    cabecalho.add("Nome");
                    cabecalho.add("CPF");
                    cabecalho.add("status_da_mensalidade");
                    jtb.setModel(new DefaultTableModel(new DependenteData().listar(), cabecalho));

                }

            }  catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro:" + e.getMessage());



        }// TO    // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jTfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfiltroActionPerformed

    }//GEN-LAST:event_jTfiltroActionPerformed

    private void jTfiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfiltroFocusGained

        jTfiltro.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jTfiltroFocusGained

    private void jTfiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfiltroFocusLost
        jTfiltro.setText("Filtrar");// TODO add your handling code here:
    }//GEN-LAST:event_jTfiltroFocusLost

    private void jTfiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfiltroKeyReleased
        
         
        try {
            if (jcbSelecione.getSelectedIndex()== 1) {
                Vector cabecalho = new Vector();
                cabecalho.add("Id");
                cabecalho.add("Nome");
                cabecalho.add("CPF");
                 cabecalho.add("status_da_mensalidade");
                jtb.setModel(new DefaultTableModel(new AssociadoData().Listar(jTfiltro.getText()), cabecalho));
            }

            if (jcbSelecione.getSelectedIndex()== 2) {
                Vector cabecalho = new Vector();
                cabecalho.add("Id");
                cabecalho.add("Nome");
                cabecalho.add("CPF");
                cabecalho.add("status_da_mensalidade");
                jtb.setModel(new DefaultTableModel(new DependenteData().Listar(jTfiltro.getText()), cabecalho));

            }
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro:" + e.getMessage());

        
    }// TODO add

        // TODO add your handling code here:
    }//GEN-LAST:event_jTfiltroKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          DefaultTableModel tableModel =(DefaultTableModel) jtb.getModel();  
                                 tableModel.setNumRows(0);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jL_tiposelecionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTfiltro;
    private javax.swing.JComboBox jcbSelecione;
    private javax.swing.JTable jtb;
    // End of variables declaration//GEN-END:variables





}
