/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Dimension;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JFrame;
import model.Funcionario;

/**
 *
 * @author Walyson
 */
public class jfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public jfPrincipal(Funcionario obj) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        if (obj.getTipo() == 1) { //comum  
            jmCadastrar.setEnabled(true);
            jmControlePagamento.setEnabled(true);
        }

        if (obj.getTipo() == 2) { //administrador
            jmCadastrar.setEnabled(true);
            jmControlePagamento.setEnabled(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiAssociado = new javax.swing.JMenuItem();
        jmiCategoria = new javax.swing.JMenuItem();
        jmiContrato = new javax.swing.JMenuItem();
        jmiDependente = new javax.swing.JMenuItem();
        jmiFuncionarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiMensalidade = new javax.swing.JMenuItem();
        jmiModalidade = new javax.swing.JMenuItem();
        jmiParentesco = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jmControlePagamento = new javax.swing.JMenu();
        jmiControlePagamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        setExtendedState(2);

        jmbPrincipal.setBackground(new java.awt.Color(153, 204, 255));
        jmbPrincipal.setForeground(new java.awt.Color(153, 204, 255));

        jmCadastrar.setText("Cadastrar");

        jmiAssociado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiAssociado.setText("Associado");
        jmiAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAssociadoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiAssociado);

        jmiCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmiCategoria.setText("Categoria");
        jmiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriaActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCategoria);

        jmiContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiContrato.setText("Contrato");
        jmiContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContratoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiContrato);

        jmiDependente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmiDependente.setText("Dependente");
        jmiDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDependenteActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiDependente);

        jmiFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmiFuncionarios.setText("Funcionário");
        jmiFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionariosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiFuncionarios);
        jmCadastrar.add(jSeparator1);

        jmiMensalidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmiMensalidade.setText("Mensalidade");
        jmiMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMensalidadeActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiMensalidade);

        jmiModalidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiModalidade.setText("Modalidade Esportiva");
        jmiModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModalidadeActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiModalidade);

        jmiParentesco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmiParentesco.setText("Parentesco");
        jmiParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiParentescoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiParentesco);

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiSair);

        jmbPrincipal.add(jmCadastrar);

        jmControlePagamento.setText("Controle de pagamento");

        jmiControlePagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiControlePagamento.setText("Controle de pagamento");
        jmiControlePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiControlePagamentoActionPerformed(evt);
            }
        });
        jmControlePagamento.add(jmiControlePagamento);

        jmbPrincipal.add(jmControlePagamento);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiControlePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiControlePagamentoActionPerformed

//           new pgto().setVisible(true); 
        GereciamentoPagamento obj = new GereciamentoPagamento();
         int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);
        obj.setVisible(true);

    }//GEN-LAST:event_jmiControlePagamentoActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiParentescoActionPerformed
        jifParentesco obj = new jifParentesco();
        jdpPrincipal.add(obj);
        
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiParentescoActionPerformed

    private void jmiModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModalidadeActionPerformed
        jifModalidade obj = new jifModalidade();        
        jdpPrincipal.add(obj);
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jmiModalidadeActionPerformed

    private void jmiMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMensalidadeActionPerformed
        jifMensalidade obj = new jifMensalidade();
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiMensalidadeActionPerformed

    private void jmiFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionariosActionPerformed
        jifFuncionario obj = new jifFuncionario();
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jmiFuncionariosActionPerformed

    private void jmiDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDependenteActionPerformed
        jifDependente obj = new jifDependente();
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiDependenteActionPerformed

    private void jmiContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContratoActionPerformed
        jifContrato obj = new jifContrato();
        int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);        
        
        obj.setVisible(true);
    }//GEN-LAST:event_jmiContratoActionPerformed

    private void jmiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriaActionPerformed
        jifCategorias obj = new jifCategorias();
        
        int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
       // obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj); 
                
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCategoriaActionPerformed

    private void jmiAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAssociadoActionPerformed
        jifAssociado obj = new jifAssociado();
             int x1 = (jdpPrincipal.getSize().width - obj.getSize().width)/2;        
        
        obj.setBounds(x1,80,obj.getSize().width,obj.getSize().height);
        jdpPrincipal.add(obj);        
        obj.setVisible(true);
    }//GEN-LAST:event_jmiAssociadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmControlePagamento;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiAssociado;
    private javax.swing.JMenuItem jmiCategoria;
    private javax.swing.JMenuItem jmiContrato;
    private javax.swing.JMenuItem jmiControlePagamento;
    private javax.swing.JMenuItem jmiDependente;
    private javax.swing.JMenuItem jmiFuncionarios;
    private javax.swing.JMenuItem jmiMensalidade;
    private javax.swing.JMenuItem jmiModalidade;
    private javax.swing.JMenuItem jmiParentesco;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables

}
