/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.DependenteData;
import data.ParentescoData;
import extras.Documentos;
import java.awt.Color;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Associado;
import model.Dependente;
import model.Parentesco;

/**
 *
 * @author MaqLab
 */
public class DependenteFrame extends javax.swing.JInternalFrame {

    Dependente obj;
    Vector<Associado> vetorAssociado;
    Vector<Parentesco> vetorParentescos;
    DependenteData DAO;
    DefaultTableModel modelo;
    Vector<Dependente> vetorDependente;
    int acao = 0;

    /**
     * Creates new form DependenteFrame
     */
    public DependenteFrame() {
        initComponents();
        initComponents();
        obj = new Dependente();
        vetorAssociado = new Vector<Associado>();
        vetorParentescos = new Vector<Parentesco>();
        vetorDependente = new Vector<Dependente>();
        DAO = new DependenteData();

    }

    public DependenteFrame(String nome) {
        initComponents();
        initComponents();
        obj = new Dependente();
        vetorAssociado = new Vector<Associado>();
        vetorParentescos = new Vector<Parentesco>();
        DAO = new DependenteData();
        jtAssociado.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlDataNascimento = new javax.swing.JLabel();
        jftDataNascimento = new javax.swing.JFormattedTextField();
        jlDependente = new javax.swing.JLabel();
        jtDependente = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlRg = new javax.swing.JLabel();
        jtRg = new javax.swing.JFormattedTextField();
        jlCpf = new javax.swing.JLabel();
        jtCpf = new javax.swing.JFormattedTextField();
        jlParentesco = new javax.swing.JLabel();
        jcbParentesco = new javax.swing.JComboBox();
        jlDependentes = new javax.swing.JLabel();
        jtAssociado = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabel9.setBackground(new java.awt.Color(0, 0, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dependente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlDataNascimento.setBackground(new java.awt.Color(0, 0, 102));
        jlDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDataNascimento.setForeground(new java.awt.Color(0, 0, 102));
        jlDataNascimento.setText("Data Nascimento");

        jftDataNascimento.setEditable(false);
        jftDataNascimento.setBackground(new java.awt.Color(195, 195, 195));
        try {
            jftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftDataNascimentoActionPerformed(evt);
            }
        });

        jlDependente.setBackground(new java.awt.Color(0, 0, 102));
        jlDependente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDependente.setForeground(new java.awt.Color(0, 0, 102));
        jlDependente.setText("Dependente");

        jtDependente.setEditable(false);
        jtDependente.setBackground(new java.awt.Color(195, 195, 195));
        jtDependente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtDependente.setToolTipText("Digite o nome ");

        jlEndereco.setBackground(new java.awt.Color(0, 0, 102));
        jlEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEndereco.setForeground(new java.awt.Color(0, 0, 102));
        jlEndereco.setText("Endereço");

        jtEndereco.setEditable(false);
        jtEndereco.setBackground(new java.awt.Color(195, 195, 195));
        jtEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtEndereco.setToolTipText("Digite o endereço");

        jlTelefone.setBackground(new java.awt.Color(0, 0, 102));
        jlTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTelefone.setForeground(new java.awt.Color(0, 0, 102));
        jlTelefone.setText("Telefone");

        jlEmail.setBackground(new java.awt.Color(0, 0, 102));
        jlEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(0, 0, 102));
        jlEmail.setText("E-mail");

        jtEmail.setEditable(false);
        jtEmail.setBackground(new java.awt.Color(195, 195, 195));
        jtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtEmail.setToolTipText("Digite o email");

        jlRg.setBackground(new java.awt.Color(0, 0, 102));
        jlRg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlRg.setForeground(new java.awt.Color(0, 0, 102));
        jlRg.setText("RG");

        jtRg.setEditable(false);
        jtRg.setBackground(new java.awt.Color(195, 195, 195));
        jtRg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtRg.setToolTipText("Digite o RG");
        try {
            jtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlCpf.setBackground(new java.awt.Color(0, 0, 102));
        jlCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlCpf.setForeground(new java.awt.Color(0, 0, 102));
        jlCpf.setText("CPF");

        jtCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtCpf.setToolTipText("Digite o CPF");
        try {
            jtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlParentesco.setBackground(new java.awt.Color(0, 0, 102));
        jlParentesco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlParentesco.setForeground(new java.awt.Color(0, 0, 102));
        jlParentesco.setText("Parentesco");

        jcbParentesco.setBackground(new java.awt.Color(195, 195, 195));
        jcbParentesco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbParentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcbParentesco.setToolTipText("Selecione o Parentesco");
        jcbParentesco.setEnabled(false);

        jlDependentes.setBackground(new java.awt.Color(0, 0, 102));
        jlDependentes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDependentes.setForeground(new java.awt.Color(0, 0, 102));
        jlDependentes.setText("Associado");

        jtAssociado.setEditable(false);
        jtAssociado.setBackground(new java.awt.Color(195, 195, 195));
        jtAssociado.setToolTipText("Associado");
        jtAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAssociadoActionPerformed(evt);
            }
        });

        jtTelefone.setEditable(false);
        jtTelefone.setBackground(new java.awt.Color(195, 195, 195));
        try {
            jtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("( ## ) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtTelefone.setText("(  )    -        ");
        jtTelefone.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlDependente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlRg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDependentes)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlParentesco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtDependente)
                                .addComponent(jtEndereco)
                                .addComponent(jtEmail)
                                .addComponent(jtAssociado)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jcbParentesco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setForeground(new java.awt.Color(153, 204, 255));

        jbNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAssociadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAssociadoActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed

        jftDataNascimento.setEditable(true);
        jtDependente.setEditable(true);
        jtEndereco.setEditable(true);
        jtEmail.setEditable(true);
        jtTelefone.setEditable(true);
        jtRg.setEditable(true);
        jtCpf.setEditable(true);
        jtAssociado.setEditable(false);
        jcbParentesco.setEnabled(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(false);
        limparCampos();
        Color whiteColor = Color.WHITE;
        jftDataNascimento.setBackground(whiteColor);
        jtDependente.setBackground(whiteColor);
        jtEndereco.setBackground(whiteColor);
        jtEmail.setBackground(whiteColor);
        jtTelefone.setBackground(whiteColor);
        jtAssociado.setBackground(whiteColor);
        jtRg.setBackground(whiteColor);
        jtCpf.setBackground(whiteColor);
        jtAssociado.setBackground(whiteColor);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (AssociadoFrame.vetorDependentes == null) {
                        AssociadoFrame.vetorDependentes = new Vector<>();
                    }
                    AssociadoFrame.vetorDependentes.add(obj);
                    AssociadoFrame.mostrarDependentes();
                    JOptionPane.showMessageDialog(this, "Salvo");
                    limparCampos();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvo " + ex.getMessage());
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        jftDataNascimento.setEditable(true);
        jtDependente.setEditable(true);
        jtEndereco.setEditable(true);
        jtEmail.setEditable(true);
        jtTelefone.setEditable(true);
        jtAssociado.setText(null);
        jtRg.setEditable(true);
        jtCpf.setEditable(true);
        jtAssociado.setEditable(true);
        jcbParentesco.setEnabled(true);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        limparCampos();
        Color grayColor = new Color(195, 195, 195);
        jftDataNascimento.setBackground(grayColor);
        jtDependente.setBackground(grayColor);
        jtEndereco.setBackground(grayColor);
        jtEmail.setBackground(grayColor);
        jtTelefone.setBackground(grayColor);
        jtAssociado.setBackground(grayColor);
        jtRg.setBackground(grayColor);
        jtCpf.setBackground(grayColor);
        jtAssociado.setBackground(grayColor);
        acao = 1;
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        try {
            DAO = new DependenteData();
            obj = DAO.pesquisar(Documentos.normalizarCPF(jtCpf.getText()));
            if (DAO.excluir(obj.getId())) {
                JOptionPane.showMessageDialog(this, "Excluido com sucesso !");
                jbCancelarActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir " + ex.getMessage());
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        ParentescoData DAOParentesco = new ParentescoData();
        try {
            vetorParentescos = DAOParentesco.carregarCombo();
            jcbParentesco.setModel(new DefaultComboBoxModel(vetorParentescos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erro " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jftDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftData_NascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftData_NascimentoActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed

        try {
            DAO = new DependenteData();
            obj = DAO.pesquisar(Documentos.normalizarCPF(jtCpf.getText()));
            if (obj == null) {
                JOptionPane.showMessageDialog(this, "Registro não encontrado");
            } else {
                jftDataNascimento.setText(obj.getDataNasc());
                jtDependente.setText(obj.getNome());
                jtEndereco.setText(obj.getEndereco());
                jtTelefone.setText(String.valueOf(obj.getTelefone()));
                jtEmail.setText(obj.getEmail());
                jtRg.setText(String.valueOf(obj.getRG()));
                jtCpf.setText(String.valueOf(obj.getCpf()));
                jcbParentesco.setEnabled(true);

                for (int i = 0; i < vetorParentescos.size(); i++) {
                    if (vetorParentescos.get(i).getId() == obj.getParentesco().getId()) {
                        jcbParentesco.setSelectedIndex(i);
                    }
                }
                jtAssociado.setText(String.valueOf(obj.getIdAssociado()));
                jbEditar.setEnabled(true);
                jbCancelar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbPesquisar.setEnabled(false);
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar" + ex.getMessage());
        }

    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefoneActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed

        jftDataNascimento.setEditable(true);
        jtEndereco.setEditable(true);
        jtTelefone.setEditable(true);
        jtEmail.setEditable(true);
        jtRg.setEditable(true);
        jtCpf.setEditable(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(false);
        acao = 2;
    }//GEN-LAST:event_jbEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbParentesco;
    private javax.swing.JFormattedTextField jftDataNascimento;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlDependente;
    private javax.swing.JLabel jlDependentes;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlParentesco;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtAssociado;
    public static javax.swing.JFormattedTextField jtCpf;
    public static javax.swing.JTextField jtDependente;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JFormattedTextField jtRg;
    private javax.swing.JFormattedTextField jtTelefone;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jftDataNascimento.setText(null);
        jtDependente.setText(null);
        jtEmail.setText(null);
        jtEndereco.setText(null);
        jtTelefone.setText(null);
        jtRg.setText(null);
        jtCpf.setText(null);
        jcbParentesco.setSelectedIndex(0);
    }

    private boolean validarCampos() throws Exception {
        String msg = "";

        if (jftDataNascimento.getText().equals("  /  /    ")) {
            msg += "\nData_Nascimento";
        }
        if (jtDependente.getText().equals("")) {
            msg += "\nDependente";
        }
        if (jtEndereco.getText().equals("")) {
            msg += "\nEndereco";
        }
        if (jtTelefone.getText().equals("(  )    -    ")) {
            msg += "\nTelefone";
        }
        if (jtTelefone.getText().equals("")) {
            msg += "\nEmail";
        }
        if (!Documentos.validarRG(jtRg.getText())) {
            msg += "\nRG inválido";
        }
        if (!Documentos.validarCPF(jtCpf.getText())) {
            msg += "\nCPF inválido";
        }

        if (jtAssociado.getText().equals("")) {
            msg += "\n Associado";
        }

        if (jcbParentesco.getSelectedIndex() == 0) {
            msg += "\n parentesco";
        }

        if (msg.equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Os seguintes campos devem ser preenchidos "
                    + msg, "Validar Campos", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean preencherObjeto() throws Exception {
        obj = new Dependente();
        obj.setDataNasc(jftDataNascimento.getText());
        obj.setNome(jtDependente.getText());
        obj.setEndereco(jtEndereco.getText());
        obj.setTelefone(jtTelefone.getText());
        obj.setEmail(jtEmail.getText());
        obj.setRG(Documentos.normalizarRG(jtRg.getText()));
        obj.setCpf(Documentos.normalizarCPF(jtCpf.getText()));
        obj.setParentesco(vetorParentescos.
                get(jcbParentesco.getSelectedIndex()));

        return true;
    }
}
