/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.AssociadoData;
import data.DependenteData;
import data.MensalidadeData;
import extras.PagamentoDialogo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Mensalidade;

/**
 *
 * @author MaqLab
 */
public class GereciamentoPagamento extends javax.swing.JInternalFrame {

    private static final int COLUNA_STATUS = 3;
    private static final int COLUNA_VALOR_DEVIDO = 4;

    /**
     * Creates new form NewJInternalFrame
     */
    public GereciamentoPagamento() {
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        jcbSelecione.requestFocusInWindow();
        configurarRendererStatus();
    }

    /**
     * Destaca visualmente cada linha de acordo com o status da mensalidade
     * (mesmas cores usadas na tela de Mensalidade), para o usuário identificar
     * inadimplência sem precisar ler a coluna com atenção.
     */
    private void configurarRendererStatus() {
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(column == 0 || column == COLUNA_VALOR_DEVIDO ? SwingConstants.CENTER : SwingConstants.LEFT);

                String status = String.valueOf(table.getModel().getValueAt(table.convertRowIndexToModel(row), COLUNA_STATUS));
                Color cor = corDoStatus(status);
                if (!isSelected) {
                    setBackground(Color.WHITE);
                    setForeground(cor);
                } else {
                    setForeground(cor.darker());
                }
                setFont(column == COLUNA_STATUS ? getFont().deriveFont(Font.BOLD) : getFont().deriveFont(Font.PLAIN));
                return c;
            }
        };
        jtb.setDefaultRenderer(Object.class, renderer);
        jtb.setRowHeight(24);
    }

    private Color corDoStatus(String status) {
        switch (status) {
            case "PAGO":
                return new Color(0, 128, 0);
            case "EM ATRASO":
                return new Color(178, 34, 34);
            case "VENCE EM BREVE":
                return new Color(184, 134, 11);
            case "PENDENTE":
                return new Color(70, 70, 70);
            default:
                return Color.BLACK;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbSelecione = new javax.swing.JComboBox();
        jlTipoSelecionado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTfiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Gerenciamento de Mensalidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(jLabel1)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jcbSelecione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Associado", "Dependente" }));

        jlTipoSelecionado.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jlTipoSelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jButton1.setText("Exibir Tudo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTfiltro.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jTfiltro.setForeground(new java.awt.Color(102, 102, 102));
        jTfiltro.setText("Filtrar");
        jTfiltro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfiltroFocusLost(evt);
            }
        });
        jTfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfiltroActionPerformed(evt);
            }
        });
        jTfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfiltroKeyReleased(evt);
            }
        });

        jtb.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jtb.setForeground(new java.awt.Color(0, 0, 255));
        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb);

        jButton2.setText("Limpar Tabela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jcbSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(271, 271, 271))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addComponent(jlTipoSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGap(247, 247, 247)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jcbSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jlTipoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(255, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jcbSelecione.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione Associado ou Dependente");
            return;
        }
        pesquisarEExibir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesquisarEExibir() {
        Vector cabecalho = new Vector();
        cabecalho.add("Id");
        cabecalho.add("Nome");
        cabecalho.add("CPF");
        cabecalho.add("Status da Mensalidade");
        cabecalho.add("Valor Devido");
        cabecalho.add("Próximo Vencimento");
        try {
            if (jcbSelecione.getSelectedIndex() == 1) {
                AssociadoData associadoData = new AssociadoData();
                jtb.setModel(new DefaultTableModel(associadoData.listar(textoFiltro()), cabecalho));
            }

            if (jcbSelecione.getSelectedIndex() == 2) {
                DependenteData dependenteData = new DependenteData();
                jtb.setModel(new DefaultTableModel(dependenteData.listar(textoFiltro()), cabecalho));
            }
            jlTipoSelecionado.setText("Exibindo: " + jcbSelecione.getSelectedItem());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro:" + e.getMessage());
        }
    }
    private void jTfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfiltroActionPerformed

    }//GEN-LAST:event_jTfiltroActionPerformed

    private void jTfiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfiltroFocusGained
        if (jTfiltro.getText().equals("Filtrar")) {
            jTfiltro.setText("");
        }
    }//GEN-LAST:event_jTfiltroFocusGained

    private void jTfiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfiltroFocusLost
        if (jTfiltro.getText().trim().isEmpty()) {
            jTfiltro.setText("Filtrar");
        }
    }//GEN-LAST:event_jTfiltroFocusLost

    private String textoFiltro() {
        String filtro = jTfiltro.getText().trim();
        return filtro.equals("Filtrar") ? "" : filtro;
    }

    private void jTfiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfiltroKeyReleased
        if (jcbSelecione.getSelectedIndex() == 0) {
            return;
        }
        pesquisarEExibir();
    }//GEN-LAST:event_jTfiltroKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jtb.getModel();
        tableModel.setNumRows(0);
        jlTipoSelecionado.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtbMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            exibirHistorico();
            return;
        }
        if (evt.isPopupTrigger() || javax.swing.SwingUtilities.isRightMouseButton(evt)) {
            int linha = jtb.rowAtPoint(evt.getPoint());
            if (linha < 0) {
                return;
            }
            jtb.setRowSelectionInterval(linha, linha);
            abrirMenuContexto(evt);
        }
    }

    private void abrirMenuContexto(java.awt.event.MouseEvent evt) {
        JPopupMenu menu = new JPopupMenu();

        JMenuItem itemHistorico = new JMenuItem("Ver Histórico");
        itemHistorico.addActionListener(e -> exibirHistorico());
        menu.add(itemHistorico);

        JMenuItem itemImprimir = new JMenuItem("Imprimir Carteirinha");
        itemImprimir.addActionListener(e -> imprimirCarteirinha());
        menu.add(itemImprimir);

        int linha = jtb.getSelectedRow();
        String status = linha < 0 ? "" : String.valueOf(jtb.getValueAt(linha, COLUNA_STATUS));
        JMenuItem itemRegistrarPagamento = new JMenuItem("Registrar Pagamento");
        itemRegistrarPagamento.setEnabled(linha >= 0 && !"PAGO".equals(status));
        itemRegistrarPagamento.addActionListener(e -> registrarPagamento());
        menu.add(itemRegistrarPagamento);

        menu.show(jtb, evt.getX(), evt.getY());
    }

    /** R1.8 - imprime a carteirinha do associado/dependente selecionado na tabela. */
    private void imprimirCarteirinha() {
        int linha = jtb.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um registro na tabela.");
            return;
        }
        int id = (Integer) jtb.getValueAt(linha, 0);
        String nome = String.valueOf(jtb.getValueAt(linha, 1));
        String cpf = String.valueOf(jtb.getValueAt(linha, 2));
        String status = String.valueOf(jtb.getValueAt(linha, 3));
        String tipo = jcbSelecione.getSelectedIndex() == 1 ? "Associado" : "Dependente";

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable((graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            g2d.setFont(new Font("SansSerif", Font.BOLD, 18));
            g2d.drawString("Carteirinha do Clube", 20, 30);
            g2d.setFont(new Font("SansSerif", Font.PLAIN, 14));
            g2d.drawString("Tipo: " + tipo, 20, 70);
            g2d.drawString("Id: " + id, 20, 95);
            g2d.drawString("Nome: " + nome, 20, 120);
            g2d.drawString("CPF: " + cpf, 20, 145);
            g2d.drawString("Status da mensalidade: " + status, 20, 170);
            return Printable.PAGE_EXISTS;
        });

        if (job.printDialog()) {
            try {
                job.print();
                JOptionPane.showMessageDialog(this, "Carteirinha enviada para impressão.");
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao imprimir: " + ex.getMessage());
            }
        }
    }

    private void registrarPagamento() {
        int linha = jtb.getSelectedRow();
        if (linha < 0) {
            return;
        }
        int id = (Integer) jtb.getValueAt(linha, 0);
        String nome = String.valueOf(jtb.getValueAt(linha, 1));
        try {
            MensalidadeData mdao = new MensalidadeData();
            Mensalidade pendente = jcbSelecione.getSelectedIndex() == 1
                    ? mdao.pesquisarPendentePorAssociado(id)
                    : mdao.pesquisarPendentePorDependente(id);

            if (pendente == null) {
                JOptionPane.showMessageDialog(this, "Nenhuma mensalidade pendente encontrada para " + nome + ".");
                return;
            }

            PagamentoDialogo.Resultado pagamento = PagamentoDialogo.coletar(this, pendente.getValor());
            if (pagamento == null) {
                return;
            }

            String hoje = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
            if (mdao.registrarPagamento(pendente.getId(), hoje, pagamento.formaPagamento, pagamento.valorRecebido, pagamento.troco)) {
                JOptionPane.showMessageDialog(this, "Pagamento registrado com sucesso!");
                pesquisarEExibir();
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível registrar o pagamento.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar pagamento: " + ex.getMessage());
        }
    }

    private void exibirHistorico() {
        int linha = jtb.getSelectedRow();
        if (linha < 0) {
            return;
        }
        int id = (Integer) jtb.getValueAt(linha, 0);
        String nome = String.valueOf(jtb.getValueAt(linha, 1));
        try {
            MensalidadeData mdao = new MensalidadeData();
            Vector<Mensalidade> historico = jcbSelecione.getSelectedIndex() == 1
                    ? mdao.historicoPorAssociado(id)
                    : mdao.historicoPorDependente(id);

            if (historico.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhuma mensalidade encontrada para " + nome + ".");
                return;
            }

            StringBuilder texto = new StringBuilder("Histórico de mensalidades - " + nome + "\n\n");
            texto.append(String.format("%-10s %-14s %-14s %-10s%n", "Mês Ref.", "Vencimento", "Pagamento", "Valor"));
            for (Mensalidade m : historico) {
                String pagamento = m.getDataPgto().isEmpty() ? "PENDENTE" : m.getDataPgto();
                texto.append(String.format("%-10s %-14s %-14s R$ %.2f%n", m.getMesRef(), m.getDataVenc(), pagamento, m.getValor()));
            }
            JOptionPane.showMessageDialog(this, texto.toString(), "Histórico de Pagamentos", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar histórico: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jlTipoSelecionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTfiltro;
    private javax.swing.JComboBox jcbSelecione;
    private javax.swing.JTable jtb;
    // End of variables declaration//GEN-END:variables

}
