/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Data.AssociadoData;
import Data.DependenteData;
import Data.FuncionarioData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.Associado;
import model.Dependente;

/**
 *
 * @author MaqLab
 */
public class jifAssociado extends javax.swing.JInternalFrame {

    static Associado obj;
    Vector<Associado> vetorAssociados;
    public static Vector<Dependente> vetorDependentes;
    AssociadoData DAO;
    int acao = 0;

    /**
     * Creates new form jifAssociado
     */
    public jifAssociado() {
        initComponents();
        obj = new Associado();
        vetorAssociados = new Vector<Associado>();
        vetorDependentes = new Vector<Dependente>();
        DAO = new AssociadoData();
    }

    public static void mostrarDependentes() {
        DefaultTableModel model
                = (DefaultTableModel) jtbDependentes.getModel();

        if (vetorDependentes.size() > 0) {
            int qtdLinhas = model.getRowCount();
            for (int i = 0; i < qtdLinhas; i++) { //limpa a tabela 
                model.removeRow(i); //remove a linha
            }
            for (int i = 0; i < vetorDependentes.size(); i++) {// adiciona a linha
                model.addRow(new String[]{
                    "" + vetorDependentes.get(i).getId(),
                    vetorDependentes.get(i).getNome(),
                    "" + vetorDependentes.get(i).getCpf()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlAssoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlData_Nascimento = new javax.swing.JLabel();
        jftData_Nascimento = new javax.swing.JFormattedTextField();
        jtAssociado = new javax.swing.JTextField();
        jlAssociado = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlRG = new javax.swing.JLabel();
        jtRG = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jtCPF = new javax.swing.JTextField();
        jlProfissao = new javax.swing.JLabel();
        jtProfissao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDependentes = new javax.swing.JTable();
        jbAdicionar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jtTelefone = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jlAssoc.setBackground(new java.awt.Color(0, 0, 102));
        jlAssoc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlAssoc.setForeground(new java.awt.Color(0, 0, 102));
        jlAssoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAssoc.setText("Associado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jlAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlAssoc, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlData_Nascimento.setBackground(new java.awt.Color(0, 0, 102));
        jlData_Nascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlData_Nascimento.setForeground(new java.awt.Color(0, 0, 102));
        jlData_Nascimento.setText("Data Nascimento");

        jftData_Nascimento.setEditable(false);
        try {
            jftData_Nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftData_Nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftData_NascimentoActionPerformed(evt);
            }
        });

        jtAssociado.setEditable(false);
        jtAssociado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtAssociado.setToolTipText("Digite o nome ");
        jtAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAssociadoActionPerformed(evt);
            }
        });

        jlAssociado.setBackground(new java.awt.Color(0, 0, 102));
        jlAssociado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlAssociado.setForeground(new java.awt.Color(0, 0, 102));
        jlAssociado.setText("Associado");

        jlEndereco.setBackground(new java.awt.Color(0, 0, 102));
        jlEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEndereco.setForeground(new java.awt.Color(0, 0, 102));
        jlEndereco.setText("Endereço");

        jtEndereco.setEditable(false);
        jtEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtEndereco.setToolTipText("Digite o Endereço");

        jlTelefone.setBackground(new java.awt.Color(0, 0, 102));
        jlTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTelefone.setForeground(new java.awt.Color(0, 0, 102));
        jlTelefone.setText("Telefone");

        jlEmail.setBackground(new java.awt.Color(0, 0, 102));
        jlEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(0, 0, 102));
        jlEmail.setText("E-mail");

        jtEmail.setEditable(false);
        jtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtEmail.setToolTipText("Digite o email");

        jlRG.setBackground(new java.awt.Color(0, 0, 102));
        jlRG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlRG.setForeground(new java.awt.Color(0, 0, 102));
        jlRG.setText("RG");

        jtRG.setEditable(false);
        jtRG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtRG.setToolTipText("Digite o RG");
        jtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRGActionPerformed(evt);
            }
        });

        jlCPF.setBackground(new java.awt.Color(0, 0, 102));
        jlCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlCPF.setForeground(new java.awt.Color(0, 0, 102));
        jlCPF.setText("CPF");

        jtCPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtCPF.setToolTipText("Digite o CPF");

        jlProfissao.setBackground(new java.awt.Color(0, 0, 102));
        jlProfissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlProfissao.setForeground(new java.awt.Color(0, 0, 102));
        jlProfissao.setText("Profissão");

        jtProfissao.setEditable(false);
        jtProfissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtProfissao.setToolTipText("Digite a profissão");

        jtbDependentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Dependente", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbDependentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDependentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDependentes);

        jbAdicionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAdicionar.setText("+");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbRemover.setText("-");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jtTelefone.setEditable(false);
        try {
            jtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("( ## ) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtTelefone.setText("(  )    -        ");
        jtTelefone.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEndereco)
                            .addComponent(jlAssociado)
                            .addComponent(jlTelefone)
                            .addComponent(jlEmail)
                            .addComponent(jlRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlProfissao))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtAssociado)
                            .addComponent(jtEndereco)
                            .addComponent(jtEmail)
                            .addComponent(jtProfissao)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jlCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAssociado)
                    .addComponent(jtAssociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco)
                    .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRG)
                    .addComponent(jtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCPF)
                    .addComponent(jtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlProfissao)
                    .addComponent(jtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jbRemover)
                        .addGap(38, 38, 38))))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setForeground(new java.awt.Color(153, 204, 255));
        jPanel3.setToolTipText("");

        jbNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar)
                    .addComponent(jbPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        if (jtbDependentes.getSelectedRow() > 0) {
            DefaultTableModel model = (DefaultTableModel) jtbDependentes.getModel();
            model.removeRow(jtbDependentes.getSelectedRow());
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed

        jifDependente ini = new jifDependente(jtAssociado.getText());
        jfPrincipal.jdpPrincipal.add(ini);
        ini.toFront();
        ini.setVisible(true);

//        //atualiza o jtable
//        DefaultTableModel model
//                = (DefaultTableModel) jtbDependentes.getModel();
//        
//        model.addRow(new String[]{"sdfas sadf asdf "});

    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed

        jftData_Nascimento.setEditable(true);
        jtAssociado.setEditable(true);
        jtEndereco.setEditable(true);
        jtTelefone.setEditable(true);
        jtEmail.setEditable(true);
        jtRG.setEditable(true);
        jtProfissao.setEditable(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbPesquisar.setEnabled(false);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        limparCampos();
        acao = 1;
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    //inlcui associado
                    if (acao == 1) {
                        if (DAO.incluir(obj)) {
                            //percorrer o vetor de dependentes inlcuindo cada depende
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                            jbCancelarActionPerformed(evt);
                            // cadastrarDependentes();
                            DefaultTableModel tableModel = (DefaultTableModel) jtbDependentes.getModel();
                            tableModel.setNumRows(0);
                        }
                    }
                    if (acao == 2) {
                        if (DAO.editar(obj)) {
                            JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                            jbCancelarActionPerformed(evt);

                        }

                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar" + ex.getMessage());
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void cadastrarDependentes() throws Exception {
        for (int i = 0; i < vetorDependentes.size(); i++) {
            Dependente dep = new Dependente();
            dep.setId(vetorDependentes.get(i).getId());
            dep.setNome(vetorDependentes.get(i).getNome());
            dep.setData_nasc(vetorDependentes.get(i).getData_nasc());
            dep.setEndereco(vetorDependentes.get(i).getEndereco());
            dep.setTelefone(vetorDependentes.get(i).getTelefone());
            dep.setEmail(vetorDependentes.get(i).getEmail());
            dep.setRG(vetorDependentes.get(i).getRG());
            dep.setCpf(vetorDependentes.get(i).getCpf());
            dep.setParentesco(vetorDependentes.get(i).getParentesco());
            dep.setIdAssociado(obj.getId());

            DependenteData depDB = new DependenteData();
            depDB.incluir(dep);
        }
        vetorDependentes.clear();
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:

    }

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        jftData_Nascimento.setEditable(true);
        jtAssociado.setEditable(true);
        jtEndereco.setEditable(true);
        jtTelefone.setEditable(true);
        jtEmail.setEditable(true);
        jtRG.setEditable(true);
        jtCPF.setEditable(true);
        jtProfissao.setEditable(true);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbExcluir.setEnabled(false);
        limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed

        jftData_Nascimento.setEditable(true);
        jtAssociado.setEditable(true);
        jtEndereco.setEditable(true);
        jtEmail.setEditable(true);
        jtRG.setEditable(true);
        jtCPF.setEditable(true);
        jtProfissao.setEditable(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(false);
        acao = 2;
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        try {
            if (DAO.excluir(Integer.parseInt(jtAssociado.getText()))) {
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso !");
                jbCancelarActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro ");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + ex.getMessage());
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtbDependentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDependentesMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jtbDependentesMouseClicked

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed

        try {
            DAO = new AssociadoData();
            obj = DAO.pesquisar(jtCPF.getText());
            if (obj == null) {
                JOptionPane.showMessageDialog(this, "Registro não encontrado");
            } else {
                jtAssociado.setText(obj.getNome());

                String dataNascimento = obj.getData_nasc();
                if (dataNascimento != null && !dataNascimento.trim().isEmpty()) {
                    // Convert date format from yyyy-MM-dd to dd/MM/yyyy
                    SimpleDateFormat originalFormat = new SimpleDateFormat("yyyy-MM-dd");
                    SimpleDateFormat targetFormat = new SimpleDateFormat("dd/MM/yyyy");
                    try {
                        Date date = originalFormat.parse(dataNascimento);
                        String formattedDate = targetFormat.format(date);
                        jftData_Nascimento.setText(formattedDate);
                    } catch (ParseException e) {
                        // Handle parsing error
                        JOptionPane.showMessageDialog(this, "Erro ao formatar a data: " + e.getMessage());
                    }
                } else {
                    jftData_Nascimento.setText(""); // Handle null or empty date
                }

                jtEndereco.setText(obj.getEndereco());
                jtTelefone.setText(String.valueOf(obj.getTelefone()));
                jtEmail.setText(obj.getEmail());
                jtRG.setText(String.valueOf(obj.getRG()));
                jtCPF.setText(String.valueOf(obj.getCpf()));
                jtProfissao.setText(obj.getProfissao());
                jbEditar.setEnabled(true);
                jbCancelar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbPesquisar.setEnabled(false);
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar" + ex.getMessage());
        }

    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRGActionPerformed

    private void jtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefoneActionPerformed

    private void jtAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAssociadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAssociadoActionPerformed

    private void jftData_NascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftData_NascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftData_NascimentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JFormattedTextField jftData_Nascimento;
    private javax.swing.JLabel jlAssoc;
    private javax.swing.JLabel jlAssociado;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlData_Nascimento;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlProfissao;
    private javax.swing.JLabel jlRG;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtAssociado;
    private javax.swing.JTextField jtCPF;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtProfissao;
    private javax.swing.JTextField jtRG;
    private javax.swing.JFormattedTextField jtTelefone;
    public static javax.swing.JTable jtbDependentes;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {

        jftData_Nascimento.setText(null);
        jtAssociado.setText(null);
        jtEndereco.setText(null);
        jtTelefone.setText(null);
        jtEmail.setText(null);
        jtRG.setText(null);
        jtCPF.setText(null);
        jtProfissao.setText(null);
    }

    private boolean validarCampos() throws Exception {
        String msg = "";
        if (jftData_Nascimento.getText().equals("  /  /    ")) {
            msg += "\nData_Nascimento";
        }
        if (jtAssociado.getText().equals("")) {
            msg += "\nAssociado";
        }
        if (jtEndereco.getText().equals("")) {
            msg += "\nEndereco";
        }
        if (jtTelefone.getText().equals("(  )    -    ")) {
            msg += "\nTelefone";
        }
        if (jtEmail.getText().equals("")) {
            msg += "\nEmail";
        }
        if (jtRG.getText().equals("")) {
            msg += "\nRG";
        }
        if (jtCPF.getText().equals("")) {
            msg += "\nCPF";
        }
        if (jtProfissao.getText().equals("")) {
            msg += "\nProfissao";
        }

        if (msg.equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Os seguintes campos devem ser preenchidos"
                    + msg, "Validar Campos", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean preencherObjeto() throws Exception {
        obj = new Associado();
        obj.setData_nasc(jftData_Nascimento.getText());
        obj.setNome(jtAssociado.getText());
        obj.setEndereco(jtEndereco.getText());
        obj.setTelefone(jtTelefone.getText());
        obj.setEmail(jtEmail.getText());
        obj.setRG(jtRG.getText());
        obj.setCpf(jtCPF.getText());
        obj.setProfissao(jtProfissao.getText());
        obj.setDependente(vetorDependentes);
        return true;
    }

}
