/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Data.CategoriaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Modalidade_esportiva;

/**
 *
 * @author MaqLab
 */
public class jifCategorias extends javax.swing.JInternalFrame {
     Categoria obj;
    Vector<Modalidade_esportiva> vetorModalidade_esportiva;
    CategoriaData DAO;
    /**
     * Creates new form jifCategorias
     */
    public jifCategorias() {
        initComponents();
         obj = new Categoria();
        vetorModalidade_esportiva = new Vector<Modalidade_esportiva>();
        DAO = new CategoriaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLvalor = new javax.swing.JLabel();
        jBnovo = new javax.swing.JButton();
        jTdescricao = new javax.swing.JTextField();
        jLid = new javax.swing.JLabel();
        jLid1 = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JButton();
        jLdescricao = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jTid = new javax.swing.JTextField();
        jTvalor = new javax.swing.JFormattedTextField();
        jTvalor = new extras.JMoneyField();
        //jFp_Precocusto = new extras.Moeda();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLvalor.setText("Valor");

        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jTdescricao.setToolTipText("Digite a descrição");

        jLid.setText("ID");

        jLid1.setText("CATEGORIA");

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.setMaximumSize(null);
        jbExcluir.setMinimumSize(new java.awt.Dimension(79, 23));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLdescricao.setText("Descrição");

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.setMaximumSize(null);
        jbEditar.setMinimumSize(new java.awt.Dimension(79, 23));
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBsalvar.setText("Salvar");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jTid.setToolTipText("Digite o id");
        jTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidActionPerformed(evt);
            }
        });

        jTvalor.setEditable(false);
        jTvalor.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLvalor)
                            .addComponent(jLdescricao)
                            .addComponent(jLid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLid1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBnovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBsalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPesquisar)
                                .addGap(31, 31, 31)
                                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcancelar)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLid1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdescricao)
                    .addComponent(jTdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLvalor)
                    .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar)
                    .addComponent(jBsalvar)
                    .addComponent(jBnovo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:

        jTid.setEditable(true);
        jTdescricao.setEditable(true);
        jTvalor.setEditable(true);
        jBnovo.setEnabled(false);
        jbPesquisar.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBcancelar.setEnabled(true);
        jTid.requestFocus();
        limparCampos();
        //   acao = 1;
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // if(jTid.getText().equals("")){
            //  JOptionPane.showMessageDialog(this, "Digite o id");
            // } else {
            //  try {
                //     if(DAO.excluir(Integer.parseInt(jTid.getText()))){
                    //     JOptionPane.showMessageDialog(this, "Registro excluído com sucesso !");
                    //         jBcancelarActionPerformed(evt);
                    //     } else {
                    //         JOptionPane.showMessageDialog(this, "Não foi possível excluir o registro");
                    //   }
                // } catch (Exception e) {
                //    JOptionPane.showMessageDialog(this, "Erro ao excluir:" + e.getMessage());
                // }
            //  }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        jTid.setEditable(false);
        // jTdescricao.setEditable(true);
        // jTvalor.setEditable(true);
        jBnovo.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBcancelar.setEnabled(true);
        jbPesquisar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        // acao=2;
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        //if(jTid.getText().equals("")){
            //  JOptionPane.showMessageDialog(this, "Digite um id");
            // } else {
            //  try {
                //  DAO = new CategoriaData();
                //  obj = DAO.pesquisar(Integer.parseInt(jTid.getText()));
                //  if(obj==null){
                    //      JOptionPane.showMessageDialog(this, "Registro não encontrado !");
                    //  } else {
                    //     jTdescricao.setText(obj.getDescricao());
                    //    jTvalor.setText(""+obj.getValor());
                    //ou jtPreco.setText(String.valueOf(obj.getPreco()));
                    //     jbEditar.setEnabled(true);
                    //    jbExcluir.setEnabled(true);
                    //   }
                // } catch (Exception ex) {
                // JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + ex.getMessage());
                // }
            // }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:

        jTid.setEditable(true);
        jTdescricao.setEditable(false);
        jTvalor.setEditable(false);
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBcancelar.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jTid.requestFocus();
        limparCampos();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        try {
            if(validarCampos()){
                obj = new Categoria();
                if(preencherObjeto()){
                    DAO = new CategoriaData();
                    //   if(acao==1) { //incluir
                        if(DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                            jBcancelarActionPerformed(evt);
                        }}
                        //  if(acao==2){
                            //    if(DAO.editar(obj)){
                                //     JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                                //    jBcancelarActionPerformed(evt);
                                //    }}
                        //   }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar" +
                    ex.getMessage());
            }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLid1;
    private javax.swing.JLabel jLvalor;
    private javax.swing.JTextField jTdescricao;
    private javax.swing.JTextField jTid;
    private javax.swing.JFormattedTextField jTvalor;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisar;
    // End of variables declaration//GEN-END:variables

 private void limparCampos() {
        jTid.setText("");
        jTdescricao.setText("");
        jTvalor.setText("");
    }

private boolean validarCampos() throws Exception {
       String msg="";
    if(jTid.getText().equals("")){
        msg+="\nId";   }
    if(jTdescricao.getText().equals("")){
        msg+="\nDescrição";   }
    if(jTvalor.getText().equals("")){
        jTvalor.setText("0,00");
        msg+="\n Valor";}
    
    
    if(msg.equals(""))
        return true;
    else {
        JOptionPane.showMessageDialog(this, 
         "Os seguintes campos devem ser preenchidos"
         +msg,"Validar Campos",
         JOptionPane.ERROR_MESSAGE);
        return false; }
    
   }
      

private boolean preencherObjeto() throws Exception {
        obj = new Categoria();
        obj.setId(Integer.parseInt(jTid.getText()));
        obj.setDescricao(jTdescricao.getText());
        obj.setValor(Float.parseFloat(jTvalor.getText().replace(",", ".").toUpperCase()));
        
      
        return true;
    }


}
