/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Data.ContratoData;
import Data.MensalidadeData;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Contrato;
import model.Mensalidade;

/**
 *
 * @author MaqLab
 */
public class jifMensalidade extends javax.swing.JInternalFrame {
    Mensalidade  obj;
    MensalidadeData  DAO;
    int acao = 0;
    Vector<Contrato>contratos;
    
    
    /**
     * Creates new form jifMensalidade
     */
    public jifMensalidade() {
        initComponents();
        obj = new Mensalidade();
        contratos = new Vector<Contrato>();
        DAO = new MensalidadeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlId = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jlDataPgto = new javax.swing.JLabel();
        jtDatapgto = new javax.swing.JFormattedTextField();
        jlPreco = new javax.swing.JLabel();
        jlDataVenc = new javax.swing.JLabel();
        jtDataVenc = new javax.swing.JFormattedTextField();
        jlValor = new javax.swing.JLabel();
        jtValor = new javax.swing.JFormattedTextField();
        jtValor = new extras.JMoneyField();
        //jFp_Precocusto = new extras.Moeda();

        jLabel1 = new javax.swing.JLabel();
        jcNroContrato = new javax.swing.JComboBox();
        jlMesRef = new javax.swing.JLabel();
        jtMesRef = new javax.swing.JTextField();
        jtPreco = new javax.swing.JFormattedTextField();
        jtPreco = new extras.JMoneyField();
        //jFp_Precocusto = new extras.Moeda();

        jPanel3 = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MENSALIDADE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlId.setBackground(new java.awt.Color(0, 0, 102));
        jlId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlId.setForeground(new java.awt.Color(0, 0, 102));
        jlId.setText(" id");

        jtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtId.setToolTipText("Digite o id");

        jlDataPgto.setBackground(new java.awt.Color(0, 0, 102));
        jlDataPgto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDataPgto.setForeground(new java.awt.Color(0, 0, 102));
        jlDataPgto.setText("Data pgto");

        jtDatapgto.setEditable(false);
        try {
            jtDatapgto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlPreco.setBackground(new java.awt.Color(0, 0, 102));
        jlPreco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlPreco.setForeground(new java.awt.Color(0, 0, 102));
        jlPreco.setText("Preço");

        jlDataVenc.setBackground(new java.awt.Color(0, 0, 102));
        jlDataVenc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDataVenc.setForeground(new java.awt.Color(0, 0, 102));
        jlDataVenc.setText("Data Vencimento");

        jtDataVenc.setEditable(false);
        try {
            jtDataVenc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlValor.setBackground(new java.awt.Color(0, 0, 102));
        jlValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlValor.setForeground(new java.awt.Color(0, 0, 102));
        jlValor.setText("Valor");

        jtValor.setEditable(false);
        jtValor.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Numero de contrato");

        jcNroContrato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcNroContrato.setForeground(new java.awt.Color(51, 51, 51));
        jcNroContrato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>" }));
        jcNroContrato.setToolTipText("Selecione o número de contrato");
        jcNroContrato.setEnabled(false);

        jlMesRef.setBackground(new java.awt.Color(0, 0, 102));
        jlMesRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMesRef.setForeground(new java.awt.Color(0, 0, 102));
        jlMesRef.setText("Mês Referente");

        jtMesRef.setEditable(false);
        jtMesRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtMesRef.setToolTipText("Digite o mês de referência");

        jtPreco.setEditable(false);
        jtPreco.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlDataVenc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25)
                                .addComponent(jlDataPgto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jlMesRef))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jtMesRef, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jcNroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlPreco)
                            .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(371, 371, 371)
                        .addComponent(jtDatapgto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataPgto)
                    .addComponent(jtDatapgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco)
                    .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataVenc)
                    .addComponent(jtDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcNroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMesRef)
                    .addComponent(jtMesRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setForeground(new java.awt.Color(153, 204, 255));

        jbNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(jbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbEditar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed

        if(jtId.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Digite um id");
        }else{
            try{
                DAO = new MensalidadeData();
                obj = DAO.pesquisar(Integer.parseInt(jtId.getText()));
                if(obj == null){
                    JOptionPane.showMessageDialog(this, "Registro não encontrado");
                }else{
                    jtPreco.setText("" + obj.getPreco());
                    jtDatapgto.setText(obj.getData_pgto());
                    jtDataVenc.setText(obj.getData_venc());
                    jtValor.setText(""+ obj.getValor());
                    jtMesRef.setText(obj.getMes_ref());
                    jcNroContrato.setEnabled(true);
                
                     for(int i=0;i<contratos.size();i++){
                         if(contratos.get(i).getNro_contrato()==obj.getContrato().getNro_contrato())
                             jcNroContrato.setSelectedIndex(i);
                     }
                    //ou jtPreco.setText(String.valueOf(obj.getPreco()));
                    jbNovo.setEnabled(false);
                    jbSalvar.setEnabled(false);
                    jbEditar.setEnabled(true);
                    jbCancelar.setEnabled(true);
                    jbPesquisar.setEnabled(false);

                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Erro ao pesquisar: " + ex.getMessage());
            }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if(validarCampos()){
                obj = new Mensalidade();
                if(preencherObjeto()){
                    DAO = new MensalidadeData();
                    if(acao==1) { //incluir
                        if(DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso !");
                            jbCancelarActionPerformed(evt);
                        }}
                        if(acao==2){
                            if(DAO.editar(obj)){
                                JOptionPane.showMessageDialog(this, "Alterado com sucesso !");
                                jbCancelarActionPerformed(evt);
                            }}
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar" +
                        ex.getMessage());
                }      // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jtId.setEditable(true);
        jtPreco.setEditable(true);
        jtDatapgto.setEditable(true);
        jtDataVenc.setEditable(true);
        jtValor.setEditable(true);
        jtMesRef.setEditable(true);
        jcNroContrato.setEnabled(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbCancelar.setEnabled(true);
        jbPesquisar.setEnabled(false);
        jtId.requestFocus();
        limparCampos();
        acao = 1;

        // TODO add your handling code here:
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtId.setEditable(true);
        jtPreco.setEditable(false);
        jtDatapgto.setEditable(false);
        jtDataVenc.setEditable(false);
        jtValor.setEditable(false);
        jcNroContrato.setEnabled(true);
        jtMesRef.setEditable(false);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jtId.requestFocus();
        limparCampos();// TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        jtId.setEditable(false);
        jtPreco.setEditable(true);
        jtDatapgto.setEditable(true);
        jtDataVenc.setEditable(true);
        jcNroContrato.setEnabled(true);
        jtValor.setEditable(true);
        jtMesRef.setEditable(true);
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbCancelar.setEnabled(true);
        jbPesquisar.setEnabled(false);
        acao = 2;        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        ContratoData DAONroContrato = new ContratoData();
        try{
          contratos = DAONroContrato.carregarCombo();
            jcNroContrato.setModel(new DefaultComboBoxModel(contratos));
    }catch(Exception e){
       JOptionPane.showMessageDialog(this, "erro " + e.getMessage());
        }
        
          
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcNroContrato;
    private javax.swing.JLabel jlDataPgto;
    private javax.swing.JLabel jlDataVenc;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlMesRef;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlValor;
    private javax.swing.JFormattedTextField jtDataVenc;
    private javax.swing.JFormattedTextField jtDatapgto;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtMesRef;
    private javax.swing.JFormattedTextField jtPreco;
    private javax.swing.JFormattedTextField jtValor;
    // End of variables declaration//GEN-END:variables

 private void limparCampos() {
        jtId.setText("");
        jtPreco.setText("");
        jtDatapgto.setText("");
        jtDataVenc.setText("");
       jtValor.setText("");
       jtMesRef.setText("");
       jcNroContrato.setSelectedIndex(0);
       
         
    }
    private boolean validarCampos() throws Exception{
       if(jtId.getText().equals("")){
          JOptionPane.showMessageDialog(this, "Digite o id");
          jtId.requestFocus();
          return false;
       }
         if(jtPreco.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Digite o preço");
         jtPreco.setText("0,00");
         jtPreco.requestFocus();
         return false;
       }
         
          if(jtDatapgto.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Digite a Data de pagamento");
         jtDatapgto.requestFocus();
         return false;
       }
       
             if(jtDataVenc.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Digite a Data de vencimento");
         jtDataVenc.requestFocus();
         return false;
       }
       
        if(jtValor.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Digite o Valor");
         jtValor.setText("0,00");
         jtValor.requestFocus();
         return false;
       }
       
       if( jtMesRef.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Digite ao Mês de referencia");
          jtMesRef.requestFocus();
         return false;
       }
       
       if(jcNroContrato.getSelectedIndex()==0){
         JOptionPane.showMessageDialog(this, "Digite o número do contrato");
         return false;
       }

       return true;
    }
    private boolean preencherObjeto() throws Exception{
      obj.setId(Integer.parseInt(jtId.getText()));
      obj.setPreco(Float.parseFloat(jtPreco.getText().replace(",", ".").toUpperCase()));
       obj.setData_pgto(jtDatapgto.getText());
       obj.setData_venc(jtDataVenc.getText());
       obj.setValor(Float.parseFloat(jtValor.getText().replace(",", ".").toUpperCase()));
       obj.setMes_ref(jtMesRef.getText());
       obj.setContrato(contratos.
            get(jcNroContrato.getSelectedIndex()));
      return true;
    }



}
